apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-order-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: digidine.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: user-management-service
            port:
              number: 5000
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-management-service
            port:
              number: 5000
      - path: /api/admin
        pathType: Prefix
        backend:
          service:
            name: user-management-service
            port:
              number: 5000
      - path: /api/payment
        pathType: Prefix
        backend:
          service:
            name: user-management-service
            port:
              number: 5000
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: order-notification-service
            port:
              number: 5001
      - path: /api/restaurant
        pathType: Prefix
        backend:
          service:
            name: restaurant-service
            port:
              number: 5003
      - path: /api/menu
        pathType: Prefix
        backend:
          service:
            name: restaurant-service
            port:
              number: 5003