apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  jwt-secret: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lJeE1qTTBOVFkzT0Rrd0lpd2libUZ0WlNJNklrcHZhRzRnUkc5bElpd2lhV0YwSWpveE5URTJNak01TURJeWZRLlNmbEt4d1JKU01lS0tGMlFUNGZ3cE1lSmYzNlBPazZ5SlZfYWRRc3N3NWM=
  mongo-user-uri: bW9uZ29kYitzcnY6Ly9BeW9keWE6QXlvZHlhQGNsdXN0ZXIwLmNzbjRmYWcubW9uZ29kYi5uZXQvRm9vZE9yZGVyREI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  mongo-restaurant-uri: bW9uZ29kYitzcnY6Ly9zaXRobWFrYTpzaXRobWFrYTExMjJAY2x1c3Rlci5wdnF2b3FmLm1vbmdvZGIubmV0L09yZGVyX0RCP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXI=
  mongo-order-uri: bW9uZ29kYitzcnY6Ly9zaXRobWFrYTpzaXRobWFrYTExMjJAY2x1c3Rlci5wdnF2b3FmLm1vbmdvZGIubmV0L09yZGVyX0RCP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXI=
  email-user: eW91ci1lbWFpbEBnbWFpbC5jb20=
  email-pass: eW91ci1lbWFpbC1wYXNzd29yZA==